AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Infrastructure as Code Project

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-08dd5b48624e7a2c2
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e001c9271cf7f3b9  # Amazon Linux 2 AMI
      SubnetId: subnet-0c31f6a245254bccb
      KeyName: key27
